
const canvas=document.getElementById('c'),ctx=canvas.getContext('2d');
const castaData={'idle1':'assets/characters/casta/idle1.png','idle2':'assets/characters/casta/idle2.png','idle3':'assets/characters/casta/idle3.png','idle4':'assets/characters/casta/idle4.png','idle5':'assets/characters/casta/idle5.png','walk1':'assets/characters/casta/walk1.png','walk2':'assets/characters/casta/walk2.png','walk3':'assets/characters/casta/walk3.png','walk4':'assets/characters/casta/walk4.png','walk5':'assets/characters/casta/walk5.png','walk6':'assets/characters/casta/walk6.png','punch':'assets/characters/casta/punch.png','kick':'assets/characters/casta/kick.png','crouch':'assets/characters/casta/crouch.png','jump':'assets/characters/casta/jump.png','airKick':'assets/characters/casta/air-kick.png','airRecover':'assets/characters/casta/air-recover.png'};
function imgFromData(src){const im=new Image();im.src=src;return im;}
const casta={idle:imgFromData(castaData.idle1),walk:[castaData.walk1,'assets/characters/casta/walk-transition-a.png','assets/characters/casta/walk-center.png','assets/characters/casta/walk-transition-b.png','assets/characters/casta/walk-opposite.png','assets/characters/casta/walk-transition-b.png','assets/characters/casta/walk-center.png','assets/characters/casta/walk-transition-a.png'].map(imgFromData),punch:imgFromData(castaData.punch),kick:imgFromData(castaData.kick),crouch:imgFromData(castaData.crouch),jump:imgFromData(castaData.jump),airKick:imgFromData(castaData.airKick),airRecover:imgFromData(castaData.airRecover),hit:imgFromData('assets/characters/casta/hit.png'),down:imgFromData('assets/characters/casta/down.png')};
const pulido={idle:imgFromData('assets/characters/pulido/idle.png'),walk:['assets/characters/pulido/walk1.png','assets/characters/pulido/walk-transition-a.png','assets/characters/pulido/walk-center-test.png','assets/characters/pulido/walk-transition-b.png','assets/characters/pulido/walk2.png','assets/characters/pulido/walk-transition-b.png','assets/characters/pulido/walk-center-test.png','assets/characters/pulido/walk-transition-a.png'].map(src=>imgFromData(src)),punch:imgFromData('assets/characters/pulido/punch.png'),kick:imgFromData('assets/characters/pulido/kick.png'),crouch:imgFromData('assets/characters/pulido/crouch.png'),jump:imgFromData('assets/characters/pulido/jump.png'),airKick:imgFromData('assets/characters/pulido/air-kick.png'),airRecover:imgFromData('assets/characters/pulido/air-recover.png'),hit:imgFromData('assets/characters/pulido/hit.png'),down:imgFromData('assets/characters/pulido/down.png')};
const salviData={f1:'assets/characters/salvi/f1.png',f2:'assets/characters/salvi/f2.png',walkCenter:'assets/characters/salvi/walk-center.png',walkOpposite:'assets/characters/salvi/walk-opposite.png',f8:'assets/characters/salvi/f8.png',f9:'assets/characters/salvi/f9.png',f10:'assets/characters/salvi/f10.png',f11:'assets/characters/salvi/f11.png',f12:'assets/characters/salvi/f12.png',f13:'assets/characters/salvi/f13.png'};
const salvi={
  idle:imgFromData(salviData.f1),
  walk:[salviData.f2,'assets/characters/salvi/walk-transition-a.png',salviData.walkCenter,'assets/characters/salvi/walk-transition-b.png',salviData.walkOpposite,'assets/characters/salvi/walk-transition-b.png',salviData.walkCenter,'assets/characters/salvi/walk-transition-a.png'].map(imgFromData),
  punch:imgFromData(salviData.f13),
  kick:imgFromData(salviData.f9),
  crouch:imgFromData(salviData.f10),
  jump:imgFromData(salviData.f11),
  airKick:imgFromData(salviData.f12),
  airRecover:imgFromData(salviData.f8),
  hit:imgFromData('assets/characters/salvi/hit.png'),
  down:imgFromData('assets/characters/salvi/down.png')
};
const cajaman={idle:imgFromData('assets/characters/cajaman/idle.png'),walk:['assets/characters/cajaman/walk1.png','assets/characters/cajaman/walk-transition-a.png','assets/characters/cajaman/walk-center.png','assets/characters/cajaman/walk-transition-b.png','assets/characters/cajaman/walk-opposite.png','assets/characters/cajaman/walk-transition-b.png','assets/characters/cajaman/walk-center.png','assets/characters/cajaman/walk-transition-a.png'].map(src=>imgFromData(src)),punch:imgFromData('assets/characters/cajaman/punch.png'),kick:imgFromData('assets/characters/cajaman/kick.png'),crouch:imgFromData('assets/characters/cajaman/crouch.png'),jump:imgFromData('assets/characters/cajaman/jump.png'),airKick:imgFromData('assets/characters/cajaman/air-kick.png'),airRecover:imgFromData('assets/characters/cajaman/air-recover.png'),hit:imgFromData('assets/characters/cajaman/hit.png'),down:imgFromData('assets/characters/cajaman/down.png')};
const pako={idle:imgFromData('assets/characters/pako/idle.png'),walk:['assets/characters/pako/walk1.png','assets/characters/pako/walk-transition-a.png','assets/characters/pako/walk-center.png','assets/characters/pako/walk-transition-b.png','assets/characters/pako/walk-opposite.png','assets/characters/pako/walk-transition-b.png','assets/characters/pako/walk-center.png','assets/characters/pako/walk-transition-a.png'].map(src=>imgFromData(src)),punch:imgFromData('assets/characters/pako/punch.png'),kick:imgFromData('assets/characters/pako/kick.png'),crouch:imgFromData('assets/characters/pako/crouch.png'),jump:imgFromData('assets/characters/pako/jump.png'),airKick:imgFromData('assets/characters/pako/air-kick.png'),airRecover:imgFromData('assets/characters/pako/air-recover.png'),hit:imgFromData('assets/characters/pako/hit.png'),down:imgFromData('assets/characters/pako/down.png')};
const metalero={idle:imgFromData('assets/enemies/metalero/idle.png'),walk:['assets/enemies/metalero/walk1.png','assets/enemies/metalero/walk-transition-a.png','assets/enemies/metalero/walk2-final.png','assets/enemies/metalero/walk-transition-b.png','assets/enemies/metalero/walk3.png','assets/enemies/metalero/walk-transition-b.png','assets/enemies/metalero/walk2-final.png','assets/enemies/metalero/walk-transition-a.png'].map(src=>imgFromData(src)),punch:[imgFromData('assets/enemies/metalero/punch1.png'),imgFromData('assets/enemies/metalero/punch2.png')],guard:imgFromData('assets/enemies/metalero/guard.png'),hit:imgFromData('assets/enemies/metalero/hit.png'),down:imgFromData('assets/enemies/metalero/down.png')};
const yonki2={idle:imgFromData('assets/enemies/yonki2/idle.png'),walk:['assets/enemies/yonki2/walk1.png','assets/enemies/yonki2/walk-transition-a.png','assets/enemies/yonki2/walk2.png','assets/enemies/yonki2/walk-transition-b.png','assets/enemies/yonki2/walk3.png','assets/enemies/yonki2/walk-transition-b.png','assets/enemies/yonki2/walk2.png','assets/enemies/yonki2/walk-transition-a.png'].map(src=>imgFromData(src)),punch:imgFromData('assets/enemies/yonki2/punch.png'),guard:imgFromData('assets/enemies/yonki2/guard.png'),hit:imgFromData('assets/enemies/yonki2/hit.png'),down:imgFromData('assets/enemies/yonki2/down.png')};
// Segunda variante: chándal rojo oscuro y pantalón negro, sin alterar ninguna pose.
function yonkiRojoPalette(source){const result=new Image();const recolor=()=>{const sheet=document.createElement('canvas');sheet.width=source.width;sheet.height=source.height;const paint=sheet.getContext('2d');paint.drawImage(source,0,0);const pixels=paint.getImageData(0,0,sheet.width,sheet.height),d=pixels.data;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2],a=d[i+3];if(!a)continue;const y=Math.floor(i/4/sheet.width),sat=Math.max(r,g,b)-Math.min(r,g,b);const teal=b>r+18&&g>r+8&&sat>34;const purple=b>g+16&&r>g+6&&sat>32;if(!teal&&!purple)continue;const light=Math.round(r*.22+g*.56+b*.22);if(y>sheet.height*.48){d[i]=Math.max(9,Math.round(light*.34));d[i+1]=Math.max(10,Math.round(light*.36));d[i+2]=Math.max(13,Math.round(light*.41))}else{d[i]=Math.min(255,42+Math.round(light*.92));d[i+1]=Math.max(12,Math.round(light*.19));d[i+2]=Math.max(13,Math.round(light*.18))}}paint.putImageData(pixels,0,0);result.src=sheet.toDataURL('image/png')};if(source.complete)recolor();else source.addEventListener('load',recolor,{once:true});return result}
const yonki2Rojo={idle:yonkiRojoPalette(yonki2.idle),walk:yonki2.walk.map(yonkiRojoPalette),punch:yonkiRojoPalette(yonki2.punch),guard:yonkiRojoPalette(yonki2.guard),hit:yonkiRojoPalette(yonki2.hit),down:yonkiRojoPalette(yonki2.down)};
const yonki3={idle:imgFromData('assets/enemies/yonki3/idle.png'),walk:['assets/enemies/yonki3/walk1.png','assets/enemies/yonki3/walk-transition-a.png','assets/enemies/yonki3/walk2.png','assets/enemies/yonki3/walk-transition-b.png','assets/enemies/yonki3/walk3.png','assets/enemies/yonki3/walk-transition-b.png','assets/enemies/yonki3/walk2.png','assets/enemies/yonki3/walk-transition-a.png'].map(src=>imgFromData(src)),punch:imgFromData('assets/enemies/yonki3/punch.png'),guard:imgFromData('assets/enemies/yonki3/guard.png'),hit:imgFromData('assets/enemies/yonki3/hit.png'),down:imgFromData('assets/enemies/yonki3/down.png')};
const yonki3Nike={idle:imgFromData('assets/enemies/yonki3-nike-rojo/idle.png'),walk:['assets/enemies/yonki3-nike-rojo/walk1.png','assets/enemies/yonki3-nike-rojo/walk-transition-a.png','assets/enemies/yonki3-nike-rojo/walk2.png','assets/enemies/yonki3-nike-rojo/walk-transition-b.png','assets/enemies/yonki3-nike-rojo/walk3.png','assets/enemies/yonki3-nike-rojo/walk-transition-b.png','assets/enemies/yonki3-nike-rojo/walk2.png','assets/enemies/yonki3-nike-rojo/walk-transition-a.png'].map(src=>imgFromData(src)),punch:imgFromData('assets/enemies/yonki3-nike-rojo/punch.png'),guard:imgFromData('assets/enemies/yonki3-nike-rojo/guard.png'),hit:imgFromData('assets/enemies/yonki3-nike-rojo/hit.png'),down:imgFromData('assets/enemies/yonki3-nike-rojo/down.png')};
const kani2={idle:imgFromData('assets/enemies/kani2/idle.png'),walk:['assets/enemies/kani2/walk1.png','assets/enemies/kani2/walk-transition-a.png','assets/enemies/kani2/walk2.png','assets/enemies/kani2/walk-transition-b.png','assets/enemies/kani2/walk3.png','assets/enemies/kani2/walk-transition-b.png','assets/enemies/kani2/walk2.png','assets/enemies/kani2/walk-transition-a.png'].map(src=>imgFromData(src)),punch:imgFromData('assets/enemies/kani2/punch.png'),guard:imgFromData('assets/enemies/kani2/guard.png'),hit:imgFromData('assets/enemies/kani2/hit.png'),down:imgFromData('assets/enemies/kani2/down.png')};
const heavy={idle:imgFromData('assets/enemies/heavy/idle.png'),walk:['assets/enemies/heavy/walk1.png','assets/enemies/heavy/walk-transition-a.png','assets/enemies/heavy/walk-transition-b.png','assets/enemies/heavy/walk3.png','assets/enemies/heavy/walk-transition-b.png','assets/enemies/heavy/walk-transition-a.png'].map(src=>imgFromData(src)),punch:imgFromData('assets/enemies/heavy/punch.png'),guard:imgFromData('assets/enemies/heavy/guard.png'),hit:imgFromData('assets/enemies/heavy/hit.png'),down:imgFromData('assets/enemies/heavy/down.png')};
// Variante de paleta: conserva cada píxel de pose, borde y transparencia del Yonki 3.
function yonkiRubioPalette(source){const result=new Image();const recolor=()=>{const sheet=document.createElement('canvas');sheet.width=source.width;sheet.height=source.height;const paint=sheet.getContext('2d');paint.drawImage(source,0,0);const pixels=paint.getImageData(0,0,sheet.width,sheet.height),d=pixels.data;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2],a=d[i+3];if(!a)continue;const y=Math.floor(i/4/sheet.width);const blueDenim=y>sheet.height*.40&&b>r+12&&b>g+4&&g>r*.86;if(blueDenim){const light=Math.round(r*.26+g*.52+b*.22);d[i]=Math.max(10,Math.round(light*.38));d[i+1]=Math.max(11,Math.round(light*.40));d[i+2]=Math.max(13,Math.round(light*.45));continue}const warmHair=y<sheet.height*.43&&r>g*1.13&&g>b*1.04&&r<150&&g<115&&b<100;if(warmHair){const light=Math.round(r*.30+g*.52+b*.18);d[i]=Math.min(255,46+Math.round(light*1.34));d[i+1]=Math.min(255,27+Math.round(light*1.02));d[i+2]=Math.max(8,Math.round(light*.42))}}paint.putImageData(pixels,0,0);result.src=sheet.toDataURL('image/png')};if(source.complete)recolor();else source.addEventListener('load',recolor,{once:true});return result}
const yonki3Rubio={idle:yonkiRubioPalette(yonki3.idle),walk:yonki3.walk.map(yonkiRubioPalette),punch:yonkiRubioPalette(yonki3.punch),guard:yonkiRubioPalette(yonki3.guard),hit:yonkiRubioPalette(yonki3.hit),down:yonkiRubioPalette(yonki3.down)};
const jefePisosRojos={idle:imgFromData('assets/enemies/jefe-pisos-rojos/idle.png'),walk:['assets/enemies/jefe-pisos-rojos/walk1.png','assets/enemies/jefe-pisos-rojos/walk-transition-a.png','assets/enemies/jefe-pisos-rojos/walk2.png','assets/enemies/jefe-pisos-rojos/walk-transition-b.png','assets/enemies/jefe-pisos-rojos/walk3.png','assets/enemies/jefe-pisos-rojos/walk-transition-b.png','assets/enemies/jefe-pisos-rojos/walk2.png','assets/enemies/jefe-pisos-rojos/walk-transition-a.png'].map(src=>imgFromData(src)),punch:imgFromData('assets/enemies/jefe-pisos-rojos/punch.png'),guard:imgFromData('assets/enemies/jefe-pisos-rojos/guard.png'),drinkRaise:imgFromData('assets/enemies/jefe-pisos-rojos/drink-raise.png'),drink:imgFromData('assets/enemies/jefe-pisos-rojos/drink.png'),hit:imgFromData('assets/enemies/jefe-pisos-rojos/hit.png'),down:imgFromData('assets/enemies/jefe-pisos-rojos/down.png')};
let selectedCharacter='rafa';

const bg=new Image(), idleImg=new Image(), jumpImg=new Image(), punchImg=new Image(), kickImg=new Image(), airKickImg=new Image(), airRecoverImg=new Image(), crouchImg=new Image(), rafaHitImg=new Image(), rafaDownImg=new Image(), rafaWalkCenter=new Image(), walkImgs=Array.from({length:6},()=>new Image());
const carImg=new Image(),scrapCartImg=new Image(),stageClearImg=new Image();
const selectionMusic=new Audio('assets/audio/seleccion-personaje.mp3');
selectionMusic.loop=true;
selectionMusic.volume=.48;
const phaseMusic=new Audio('assets/audio/los-pisos-rojos-theme.wav?v=2');
phaseMusic.preload='auto';
phaseMusic.volume=.42;
const phaseMusicAlt=new Audio('assets/audio/los-pisos-rojos-theme.wav?v=2');
phaseMusicAlt.preload='auto';
phaseMusicAlt.volume=.42;
let activePhaseMusic=phaseMusic,phaseLoopAnimation=0,phaseFadeAnimation=0,phaseMusicStarted=false,phaseTransition=false;
function stopPhaseMusic(){phaseMusicStarted=false;phaseTransition=false;cancelAnimationFrame(phaseLoopAnimation);cancelAnimationFrame(phaseFadeAnimation);[phaseMusic,phaseMusicAlt].forEach(clip=>{clip.pause();clip.currentTime=0;clip.volume=.42})}
function watchPhaseLoop(){if(!phaseMusicStarted)return;const current=activePhaseMusic;if(!phaseTransition&&Number.isFinite(current.duration)&&current.duration-current.currentTime<=.06){phaseTransition=true;const next=current===phaseMusic?phaseMusicAlt:phaseMusic,start=performance.now();next.pause();next.currentTime=0;next.volume=0;next.play().catch(()=>{});const fade=now=>{const p=Math.min(1,(now-start)/40);current.volume=.42*(1-p);next.volume=.42*p;if(p<1){phaseFadeAnimation=requestAnimationFrame(fade)}else{current.pause();current.currentTime=0;current.volume=.42;activePhaseMusic=next;phaseTransition=false}};phaseFadeAnimation=requestAnimationFrame(fade)}phaseLoopAnimation=requestAnimationFrame(watchPhaseLoop)}
function startPhaseMusic(){stopPhaseMusic();activePhaseMusic=phaseMusic;phaseMusicStarted=true;phaseMusic.play().catch(()=>{});watchPhaseLoop()}
const punchImpactSfx=[new Audio('assets/audio/punch-impact.mp3'),new Audio('assets/audio/punch-impact-alt.mp3')];
const punchBlockSfx=new Audio('assets/audio/punch-blocked.mp3');
const knockoutSfx=[new Audio('assets/audio/knockout-2.mp3'),new Audio('assets/audio/knockout-3.mp3')];
const stageClearCheer=new Audio('assets/audio/stage-clear-cheer.mp3');
punchImpactSfx.forEach(sound=>{sound.preload='auto';sound.volume=.20});
punchBlockSfx.preload='auto';
punchBlockSfx.volume=.48;
knockoutSfx.forEach(sound=>{sound.preload='auto';sound.volume=.20});
stageClearCheer.preload='auto';
stageClearCheer.volume=.45;
let punchImpactIndex=0,knockoutIndex=0;
function playClip(source){const clip=source.cloneNode();clip.volume=source.volume;clip.play().catch(()=>{})}
function playPunchImpactSfx(){playClip(punchImpactSfx[punchImpactIndex++%punchImpactSfx.length])}
function playPunchBlockSfx(){playClip(punchBlockSfx)}
function playKnockoutSfx(){playClip(knockoutSfx[knockoutIndex++%knockoutSfx.length])}
function startStageClear(){stageClear={active:true,elapsed:0,finished:false};stageClearCheer.pause();stageClearCheer.currentTime=0;stageClearCheer.volume=.45;stageClearCheer.play().catch(()=>{})}
function playCarArrivalSound(){try{const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;const audio=new AudioContext(),now=audio.currentTime,osc=audio.createOscillator(),filter=audio.createBiquadFilter(),gain=audio.createGain();osc.type='sawtooth';osc.frequency.setValueAtTime(92,now);osc.frequency.exponentialRampToValueAtTime(46,now+1.35);filter.type='lowpass';filter.frequency.setValueAtTime(330,now);filter.Q.value=1.8;gain.gain.setValueAtTime(.001,now);gain.gain.exponentialRampToValueAtTime(.075,now+.09);gain.gain.exponentialRampToValueAtTime(.001,now+1.45);osc.connect(filter);filter.connect(gain);gain.connect(audio.destination);osc.start(now);osc.stop(now+1.47);setTimeout(()=>audio.close(),1800)}catch{}}
let sfxAudio;
function sfxContext(){try{const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return null;sfxAudio??=new AudioContext();if(sfxAudio.state==='suspended')sfxAudio.resume();return sfxAudio}catch{return null}}
function playHitSfx(){const audio=sfxContext();if(!audio)return;const now=audio.currentTime,osc=audio.createOscillator(),gain=audio.createGain();osc.type='triangle';osc.frequency.setValueAtTime(175,now);osc.frequency.exponentialRampToValueAtTime(62,now+.075);gain.gain.setValueAtTime(.001,now);gain.gain.exponentialRampToValueAtTime(.13,now+.008);gain.gain.exponentialRampToValueAtTime(.001,now+.09);osc.connect(gain);gain.connect(audio.destination);osc.start(now);osc.stop(now+.1)}
function playKnockSfx(){const audio=sfxContext();if(!audio)return;const now=audio.currentTime,osc=audio.createOscillator(),filter=audio.createBiquadFilter(),gain=audio.createGain();osc.type='sawtooth';osc.frequency.setValueAtTime(175,now);osc.frequency.exponentialRampToValueAtTime(76,now+.38);filter.type='lowpass';filter.frequency.value=620;gain.gain.setValueAtTime(.001,now);gain.gain.exponentialRampToValueAtTime(.075,now+.035);gain.gain.exponentialRampToValueAtTime(.001,now+.42);osc.connect(filter);filter.connect(gain);gain.connect(audio.destination);osc.start(now);osc.stop(now+.44)}
bg.src='assets/backgrounds/fase1-los-pisos-rojos-extended.png'; carImg.src='assets/vehicles/nissan-serena.png'; scrapCartImg.src='assets/props/carro-chatarra.png'; stageClearImg.src='assets/ui/stage-clear.png'; idleImg.src='assets/characters/rafa-king/idle.png'; jumpImg.src='assets/characters/rafa-king/jump.png'; punchImg.src='assets/characters/rafa-king/punch.png'; kickImg.src='assets/characters/rafa-king/kick.png';
airKickImg.src='assets/characters/rafa-king/air-kick.png';
airRecoverImg.src='assets/characters/rafa-king/air-recover.png';
crouchImg.src='assets/characters/rafa-king/crouch.png';
rafaHitImg.src='assets/characters/rafa-king/hit.png';
rafaDownImg.src='assets/characters/rafa-king/down.png';
walkImgs[0].src='assets/characters/rafa-king/walk1.png';
walkImgs[1].src='assets/characters/rafa-king/walk2.png';
walkImgs[2].src='assets/characters/rafa-king/walk3.png';
walkImgs[3].src='assets/characters/rafa-king/walk4.png';
walkImgs[4].src='assets/characters/rafa-king/walk5.png';
walkImgs[5].src='assets/characters/rafa-king/walk6.png';
rafaWalkCenter.src='assets/characters/rafa-king/walk-center-test.png';
const rafaWalkOpposite=imgFromData('assets/characters/rafa-king/walk-opposite.png');
const rafaWalkTransitionA=imgFromData('assets/characters/rafa-king/walk-transition-a.png');
const rafaWalkTransitionB=imgFromData('assets/characters/rafa-king/walk-transition-b.png');
const rafaWalkCycle=[
  walkImgs[0],rafaWalkTransitionA,rafaWalkCenter,rafaWalkTransitionB,
  rafaWalkOpposite,rafaWalkTransitionB,rafaWalkCenter,rafaWalkTransitionA
];
let W=0,H=0,cam=0,worldW=5198,facing=1,pixelRatio=1;
let introPhase='none',introClock=0,introCarX=-700,introWheelAngle=0,introDoorOpen=0;
// La plaza azul ocupa x=59..461 en el fondo: el coche queda centrado sobre ella.
const introCarParkX=60;
const keys={}; let zPressed=false, xPressed=false, comboHeld=false, comboPressed=false; let state='idle', attackTimer=0,crouchTimer=0,jumpActive=false,jumpT=0,jumpY=0,jumpKick=false,jumpRecover=false,walkFrame=0,walkClock=0,walkDistance=0,comparisonMode=false,playerAttackLanded=false,playerHitTimer=0,playerDead=false;
// Pulido: fases temporizadas sobre los sprites aprobados, sin cambiar ningún PNG.
const pulidoAttackTiming={punch:{windup:80,impact:45,hold:70,recover:100},kick:{windup:100,impact:55,hold:85,recover:120}};
let pulidoAttack=null,pulidoHitStopMs=0;
// Solo la cadencia visual de caminar de los enemigos: 23 % y luego otro 20 % más rápida, sin variar su velocidad real.
const enemyWalkFrameStride=9/(1.23*1.20);
const player={x:180,y:0,hp:100,maxHp:100};
const enemy={x:1160,y:0,facing:-1,state:'idle',walkDistance:0,walkFrame:0,attackTimer:0,hp:96,maxHp:96,hitTimer:0,comboHits:0,comboTimer:0,knocked:false,knockTimer:0,dead:false,deadTimer:0,hidden:true,active:false,attackLanded:false,name:'METALERO'};
const yonki={x:1510,y:0,facing:-1,state:'idle',walkDistance:0,walkFrame:0,attackTimer:0,hp:84,maxHp:84,hitTimer:0,comboHits:0,comboTimer:0,knocked:false,knockTimer:0,dead:false,deadTimer:0,hidden:true,active:false,attackLanded:false,name:'YONKI'};
const yonkiRojo={x:1690,y:0,facing:-1,state:'idle',walkDistance:0,walkFrame:0,attackTimer:0,hp:84,maxHp:84,hitTimer:0,comboHits:0,comboTimer:0,knocked:false,knockTimer:0,dead:false,deadTimer:0,hidden:true,active:false,attackLanded:false,name:'YONKI ROJO',variant:true};
const yonkiTres={x:1870,y:0,facing:-1,state:'idle',walkDistance:0,walkFrame:0,attackTimer:0,hp:92,maxHp:92,hitTimer:0,comboHits:0,comboTimer:0,knocked:false,knockTimer:0,dead:false,deadTimer:0,hidden:true,active:false,attackLanded:false,name:'YONKI'};
const yonkiTresRubio={x:2200,y:0,facing:-1,state:'idle',walkDistance:0,walkFrame:0,attackTimer:0,hp:92,maxHp:92,hitTimer:0,comboHits:0,comboTimer:0,knocked:false,knockTimer:0,dead:false,deadTimer:0,hidden:true,active:false,attackLanded:false,name:'YONKI RUBIO',variant:true};
const yonkiTresNike={x:2050,y:0,facing:-1,state:'idle',walkDistance:0,walkFrame:0,attackTimer:0,hp:92,maxHp:92,hitTimer:0,comboHits:0,comboTimer:0,knocked:false,knockTimer:0,dead:false,deadTimer:0,hidden:true,active:false,attackLanded:false,name:'KANI'};
const kani2Enemy={x:2230,y:0,facing:-1,state:'idle',walkDistance:0,walkFrame:0,attackTimer:0,hp:92,maxHp:92,hitTimer:0,comboHits:0,comboTimer:0,knocked:false,knockTimer:0,dead:false,deadTimer:0,hidden:true,active:false,attackLanded:false,name:'KANI 2'};
const heavyEnemy={x:2380,y:0,facing:-1,state:'idle',walkDistance:0,walkFrame:0,attackTimer:0,hp:138,maxHp:138,hitTimer:0,comboHits:0,comboTimer:0,knocked:false,knockTimer:0,dead:false,deadTimer:0,hidden:true,active:false,attackLanded:false,name:'HEAVY'};
const jefe={x:worldW-260,y:0,facing:-1,state:'idle',walkDistance:0,walkFrame:0,attackTimer:0,engaged:false,drinkTimer:0,drinkCooldown:480,hp:300,maxHp:300,hitTimer:0,comboHits:0,comboTimer:0,knocked:false,knockTimer:0,dead:false,deadTimer:0,hidden:true,active:false,attackLanded:false,name:'JEFE'};
const phaseWaves=[{trigger:650,barrier:1280},{trigger:1770,barrier:2580},{trigger:2910,barrier:3880},{trigger:4040,barrier:4630}];
const normalActors=[enemy,yonki,yonkiRojo,yonkiTres,yonkiTresRubio,yonkiTresNike,kani2Enemy,heavyEnemy];
const waveRosters=[[enemy,yonki,yonkiTres],[yonkiRojo,yonkiTresNike,yonkiTresRubio],[yonkiRojo,yonkiTresNike,heavyEnemy],[yonki,yonkiTres,kani2Enemy]];
let activeWave=-1,nextWave=0,bossActivated=false,activeWaveActors=[],phaseCameraLock=null;
let bossCart={active:false,phase:'none',x:0,y:0,vx:0,hit:false,throwerX:0};
let stageClear={active:false,elapsed:0,finished:false};
// Compatibilidad con la partida ya iniciada: no muestra ninguna escena de jefe.
let bossIntroActive=false;
const bossIntroScreen={classList:{remove(){}}};
const startScreen=document.getElementById('startScreen');
const mapScreen=document.getElementById('mapScreen');
const mapImage=mapScreen.querySelector('.mapImage');
mapImage.querySelector('img').src='assets/ui/mapa-torreblanca-fase1-sin-trazo.png';
const mapDistrictTorreblanca=document.createElement('div');
mapDistrictTorreblanca.className='mapDistrict mapDistrictTorreblanca';
mapDistrictTorreblanca.setAttribute('aria-hidden','true');
const mapDistrictPisos=document.createElement('div');
mapDistrictPisos.className='mapDistrict mapDistrictPisos';
mapDistrictPisos.setAttribute('aria-hidden','true');
mapImage.append(mapDistrictTorreblanca,mapDistrictPisos);
const mapTitle=document.createElement('div');
mapTitle.textContent='LOS PISOS ROJOS';
mapTitle.setAttribute('aria-hidden','true');
mapTitle.style.cssText='position:absolute;left:54.7%;top:64.3%;transform:translate(-50%,-50%);font:700 clamp(18px,2.15vw,34px) monospace;letter-spacing:.08em;color:#fff3ca;white-space:nowrap;text-shadow:0 0 4px #061020,0 0 9px #061020,0 0 15px #061020;pointer-events:none;z-index:2';
mapScreen.querySelector('.mapImage').append(mapTitle);
let mapTimer=0;
const rouletteOrder=['cajaman','casta','pako','pulido','rafa','salvi'];
const rouletteNames={cajaman:'CAJAMAN',casta:'CASTA',pako:'PAKO',pulido:'PULIDO',rafa:'RAFA KING',salvi:'SALVI'};
const rouletteCarousel=document.getElementById('rouletteCarousel');
const rouletteCards=Array.from(document.querySelectorAll('.rouletteCard'));
let rouletteIndex=4;
let rouletteRotation=-rouletteIndex*60;
function startScreenActive(){return startScreen.style.display!=='none';}
function mapScreenActive(){return mapScreen.style.display==='flex';}
function selectionScreenActive(){return document.getElementById('selectScreen').style.display!=='none';}
function updateRoulette(){rouletteCarousel.style.transform=`rotateY(${rouletteRotation}deg)`;rouletteCards.forEach(card=>card.classList.toggle('active',card.dataset.character===rouletteOrder[rouletteIndex]));}
function moveRoulette(direction){rouletteIndex=(rouletteIndex+direction+rouletteOrder.length)%rouletteOrder.length;rouletteRotation-=direction*60;updateRoulette();}
function selectRouletteCharacter(){selectCharacter(rouletteOrder[rouletteIndex]);}
function requestGameFullscreen(){const root=document.documentElement;if(!document.fullscreenElement&&root.requestFullscreen)root.requestFullscreen({navigationUI:'hide'}).catch(()=>{});}
function beginGame(){if(!startScreenActive())return;requestGameFullscreen();startScreen.style.display='none';selectionMusic.currentTime=0;selectionMusic.play().catch(()=>{});}
function beginPhaseIntro(){if(!mapScreenActive())return;clearTimeout(mapTimer);mapScreen.style.display='none';selectionMusic.pause();selectionMusic.currentTime=0;startPhaseMusic();startIntro();}
function showMapScreen(){mapScreen.style.display='flex';if(Number.isFinite(selectionMusic.mapResumeTime))selectionMusic.currentTime=selectionMusic.mapResumeTime;selectionMusic.play().catch(()=>{});clearTimeout(mapTimer);mapTimer=setTimeout(beginPhaseIntro,4000);}
document.getElementById('startButton').onclick=beginGame;
startScreen.addEventListener('click',beginGame);
document.getElementById('mapButton').onclick=beginPhaseIntro;
mapScreen.addEventListener('click',beginPhaseIntro);
rouletteCards.forEach(card=>card.onclick=()=>{const index=rouletteOrder.indexOf(card.dataset.character);if(index===rouletteIndex){selectRouletteCharacter();return;}let distance=index-rouletteIndex;if(distance>rouletteOrder.length/2)distance-=rouletteOrder.length;if(distance<-rouletteOrder.length/2)distance+=rouletteOrder.length;rouletteIndex=index;rouletteRotation-=distance*60;updateRoulette();});
updateRoulette();
function resize(){pixelRatio=Math.max(1,window.devicePixelRatio||1);W=canvas.clientWidth;H=canvas.clientHeight;canvas.width=Math.round(W*pixelRatio);canvas.height=Math.round(H*pixelRatio);ctx.setTransform(pixelRatio,0,0,pixelRatio,0,0);}
addEventListener('resize',resize); resize();
function mobileGameplayScale(value){return value}
// La versión final está pensada para móvil. Aplicamos esta misma composición en
// ordenador para que la previsualización local coincida con el teléfono.
function mobileLayout(){return true}
function applyViewportTransform(){const zoom=.8192;ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);const edgeBlend=Math.min(1,cam/(W*.32||1),Math.max(0,(worldW-W-cam)/(W*.32||1)));const anchorX=W*(.28*edgeBlend),anchorY=H*.72;ctx.setTransform(pixelRatio*zoom,0,0,pixelRatio*zoom,pixelRatio*anchorX*(1-zoom),pixelRatio*anchorY*(1-zoom));}
function laneTop(){return groundY()} function laneBottom(){return H*0.96}
function groundY(){return H*0.735} // Límite superior: borde inferior real del bordillo en la vista de juego.
player.y=laneBottom();
addEventListener('keydown',e=>{
  const k=e.key.toLowerCase();
  if(startScreenActive()){e.preventDefault();e.startScreenHandled=true;beginGame();return;}
  if(mapScreenActive()){e.preventDefault();e.mapScreenHandled=true;beginPhaseIntro();return;}
  if(selectionScreenActive()){if(k==='arrowleft'||k==='a'){e.preventDefault();moveRoulette(-1);return;}if(k==='arrowright'||k==='d'){e.preventDefault();moveRoulette(1);return;}if(k==='z'||e.key==='Enter'||e.key===' '){e.preventDefault();selectRouletteCharacter();return;}e.preventDefault();return;}
  if(playerDead){if(k==='r'){selectCharacter(selectedCharacter);}e.preventDefault();return;}
  if(k==='v'&&document.getElementById('selectScreen').style.display==='none'&&!introRunning()){comparisonMode=!comparisonMode;return;}
  if(!keys[k]){ if(k==='z')zPressed=true; if(k==='x')xPressed=true; }
  keys[k]=true;
  if(keys['z']&&keys['x']&&!comboHeld){comboPressed=true;comboHeld=true;}
  if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();
  if((k==='c'||e.key===' ')&&!jumpActive&&!introRunning()){jumpActive=true;jumpT=0;jumpY=0;jumpKick=false;state='jump';}
});
addEventListener('keyup',e=>{
  const k=e.key.toLowerCase(); keys[k]=false;
  if(!keys['z']||!keys['x']) comboHeld=false;
});
function drawBackground(){
  const scale=Math.max(H/bg.height,W/bg.width*0.62);
  const mobileSceneryScale=mobileLayout()?2.35:1;
  const ih=bg.height*scale*mobileSceneryScale;
  // En móvil se acerca solo el decorado, anclado a la calle: los personajes mantienen su escala actual.
  const iw=worldW*mobileSceneryScale;
  const ox=-cam+W*.5*(1-mobileSceneryScale),oy=H*.72*(1-mobileSceneryScale);
  ctx.drawImage(bg,ox,oy,iw,ih);
}
function carMetrics(){const width=400;return {width,height:width*carImg.height/carImg.width};}
function introRunning(){return introPhase==='arrival'||introPhase==='doors'||introPhase==='exit';}
function updateCamera(){if(phaseCameraLock!==null){cam=phaseCameraLock;return}cam+=(player.x-cam-W*.28)*.08;cam=Math.max(0,Math.min(worldW-W,cam));}
function carBlocksAt(x,y){if(introPhase!=='done')return false;const car=carMetrics(),bottom=H*.84,top=bottom-car.height;const padding=16;return x+padding>introCarParkX&&x-padding<introCarParkX+car.width&&y+padding>top&&y-padding<bottom;}
function resolveWorldCollision(previousX,previousY){const movedX=player.x,movedY=player.y;if(carBlocksAt(movedX,previousY))player.x=previousX;if(carBlocksAt(previousX,movedY))player.y=previousY;if(carBlocksAt(player.x,player.y)){player.x=previousX;player.y=previousY;}player.y=Math.max(laneTop(),Math.min(laneBottom(),player.y));}
function startIntro(){const car=carMetrics();playCarArrivalSound();introPhase='arrival';introClock=0;introCarX=-car.width-30;introWheelAngle=0;introDoorOpen=0;player.x=introCarParkX+car.width*.64;player.y=laneBottom();state='idle';}
function updateIntro(dt){const elapsed=dt/60,car=carMetrics();if(introPhase==='arrival'){introClock+=elapsed;introWheelAngle+=dt*.09;const p=Math.min(1,introClock/1.45),ease=1-Math.pow(1-p,3);introCarX=(-car.width-30)+(introCarParkX+car.width+30)*ease;if(p>=1){introCarX=introCarParkX;introPhase='doors';introClock=0;}}
 else if(introPhase==='doors'){introClock+=elapsed;introDoorOpen=Math.min(1,introClock/.55);if(introDoorOpen>=1){introPhase='exit';introClock=0;player.x=introCarParkX+car.width*.64;facing=1;state='jump';jumpY=0;walkFrame=0;walkClock=0;}}
 else if(introPhase==='exit'){introClock+=elapsed;const p=Math.min(1,introClock/.82);introDoorOpen=Math.max(0,1-p*1.2);player.x=introCarParkX+car.width*(.64+.52*p);if(p<.42){state='jump';jumpY=-Math.sin((p/.42)*Math.PI)*H*.052}else{state='walk';jumpY=0;walkClock+=dt*16.67;if(walkClock>=150){walkClock-=150;walkFrame=(walkFrame+1)%currentSet().walk.length;}}if(p>=1){introPhase='done';introDoorOpen=0;jumpY=0;state='idle';walkClock=0;walkFrame=0;zPressed=false;xPressed=false;comboPressed=false;}}
 updateCamera();}
function drawCarWheel(cx,cy,r,angle){ctx.save();ctx.translate(cx,cy);ctx.rotate(angle);ctx.fillStyle='#090b0e';ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#87909a';ctx.lineWidth=Math.max(2,r*.12);ctx.beginPath();ctx.arc(0,0,r*.62,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#d4d8dd';ctx.lineWidth=Math.max(1,r*.08);for(let i=0;i<5;i++){ctx.rotate(Math.PI*2/5);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(r*.55,0);ctx.stroke();}ctx.fillStyle='#20262d';ctx.beginPath();ctx.arc(0,0,r*.19,0,Math.PI*2);ctx.fill();ctx.restore();}
function drawCarPassengers(x,y,w,h){const people=[['rafa',idleImg],['casta',casta.idle],['pulido',pulido.idle],['salvi',salvi.idle],['cajaman',cajaman.idle],['pako',pako.idle]].filter(([name])=>name!==selectedCharacter).map(([,img])=>img);ctx.save();ctx.beginPath();ctx.rect(x+w*.530,y+h*.225,w*.192,h*.222);ctx.rect(x+w*.742,y+h*.245,w*.170,h*.202);ctx.clip();people.slice(0,4).forEach((img,index)=>{if(!img.complete)return;const height=h*.29,width=height*img.width/img.height,cx=x+w*(.565+index*.095),base=y+h*.462;ctx.save();ctx.globalAlpha=.72;ctx.drawImage(img,cx-width/2,base-height,width,height);ctx.globalCompositeOperation='source-in';ctx.fillStyle='#020407';ctx.fillRect(cx-width/2-1,base-height-1,width+2,height+2);ctx.restore();});ctx.restore();}
function drawIntroCar(){if(introPhase==='none'||!carImg.complete)return;const car=carMetrics(),x=introCarX-cam,parkingBottom=H*.84,y=parkingBottom-car.height,w=car.width,h=car.height;ctx.save();ctx.drawImage(carImg,x,y,w,h);drawCarPassengers(x,y,w,h);ctx.save();ctx.fillStyle='rgba(0,4,9,.58)';const glass=[[[.285,.335],[.382,.225],[.401,.225],[.401,.447],[.300,.447]],[[.410,.225],[.503,.225],[.503,.447],[.410,.447]],[[.530,.225],[.722,.225],[.722,.447],[.530,.447]],[[.742,.245],[.912,.263],[.925,.447],[.742,.447]]];glass.forEach(points=>{ctx.beginPath();points.forEach(([px,py],index)=>index?ctx.lineTo(x+w*px,y+h*py):ctx.moveTo(x+w*px,y+h*py));ctx.closePath();ctx.fill();});ctx.restore();drawCarWheel(x+w*.20,y+h*.82,h*.145,introWheelAngle);drawCarWheel(x+w*.82,y+h*.82,h*.145,introWheelAngle);if(introDoorOpen>0){const sx=carImg.width*.516,sy=carImg.height*.185,sw=carImg.width*.228,sh=carImg.height*.685,doorX=x+w*.516,doorY=y+h*.185,doorW=w*.228,doorH=h*.685,slide=doorW*.72*introDoorOpen;ctx.save();ctx.fillStyle='rgba(2,4,7,.94)';ctx.fillRect(doorX,doorY,doorW,doorH);ctx.drawImage(carImg,sx,sy,sw,sh,doorX+slide,doorY,doorW,doorH);ctx.restore();}ctx.restore();}
function currentSet(){if(selectedCharacter==='casta')return casta;if(selectedCharacter==='pulido')return pulido;if(selectedCharacter==='salvi')return salvi;if(selectedCharacter==='cajaman')return cajaman;if(selectedCharacter==='pako')return pako;return {idle:idleImg,walk:rafaWalkCycle,punch:punchImg,kick:kickImg,crouch:crouchImg,jump:jumpImg,airKick:airKickImg,airRecover:airRecoverImg,hit:rafaHitImg,down:rafaDownImg};}
function drawPlayer(){if(introPhase==='arrival'||introPhase==='doors')return;let s=currentSet(),img=s.idle,scale=mobileGameplayScale(selectedCharacter==='casta'?0.58:0.71);if(playerDead&&s.down)img=s.down;else if(playerHitTimer>0&&s.hit)img=s.hit;else if(state==='jumpKick'){img=s.airKick}else if(state==='jumpRecover'){img=s.airRecover}else if(state==='jump'){img=s.jump}else if(state==='punch'||state==='punchImpact'||state==='punchHold'){img=s.punch}else if(state==='kick'||state==='kickImpact'||state==='kickHold'){img=s.kick}else if(state==='crouch'){img=s.crouch}else if(state==='walk'){img=s.walk[walkFrame%s.walk.length]} const walking=state==='walk'&&!jumpActive,walkBob=walking?Math.abs(Math.sin(walkDistance*.12))*1.15:0;let w=img.width*scale,h=img.height*scale;let x=player.x-cam-w/2;let baseY=player.y;let y=baseY-h+jumpY-walkBob;ctx.save();if(playerDead&&!s.down){ctx.globalAlpha=.34;ctx.translate(x+w/2,y+h);ctx.rotate(-Math.PI/2);ctx.translate(-x-w/2,-y-h)}else if(playerHitTimer>0&&!s.hit)ctx.globalAlpha=playerHitTimer%4<2?.35:1;if(facing<0){ctx.translate(x+w,y);ctx.scale(-1,1);ctx.drawImage(img,0,0,w,h)}else ctx.drawImage(img,x,y,w,h);ctx.restore();if(jumpActive){ctx.save();ctx.globalAlpha=.28;ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(player.x-cam,player.y+4,28,7,0,0,Math.PI*2);ctx.fill();ctx.restore();}}
function combatActors(){return [...normalActors,jefe].filter(actor=>actor.active)}
function enemySet(actor){if(actor===enemy)return metalero;if(actor===yonki)return yonki2;if(actor===yonkiRojo)return yonki2Rojo;if(actor===yonkiTresNike)return yonki3Nike;if(actor===kani2Enemy)return kani2;if(actor===heavyEnemy)return heavy;return actor.variant?yonki3Rubio:yonki3}
function resetWaveActor(actor,x,y,slot=0){const lane=[-54,0,54][slot]||0;Object.assign(actor,{x,y,facing:-1,state:'idle',walkDistance:0,walkFrame:0,attackTimer:0,attackLanded:false,hp:actor.maxHp,hitTimer:0,guardTimer:0,guardCooldown:0,comboHits:0,comboTimer:0,knocked:false,knockTimer:0,dead:false,deadTimer:0,hidden:false,active:true,strafeClock:0,aiLane:lane+(Math.random()*18-9),attackCooldown:slot*13,aiPhase:slot*2.3})}
function activateWave(index){phaseCameraLock=cam;activeWaveActors=waveRosters[index];normalActors.forEach(actor=>{if(!activeWaveActors.includes(actor)){actor.active=false;actor.hidden=true}});activeWaveActors.forEach((actor,slot)=>{const fromRight=slot!==1;const x=fromRight?phaseCameraLock+W+34+slot*44:phaseCameraLock-34;resetWaveActor(actor,x,laneBottom()+[-18,10,-2][slot],slot)});activeWave=index}
function activateBoss(){resetWaveActor(jefe,worldW+310,laneBottom());jefe.engaged=false;jefe.drinkTimer=0;jefe.drinkCooldown=480;bossCart={active:true,phase:'entry',x:worldW+150,y:laneBottom(),vx:0,hit:false,throwerX:0};bossActivated=true}
function updatePhaseWaves(){if(activeWave>=0&&activeWaveActors.every(actor=>actor.dead)){activeWave=-1;nextWave++;activeWaveActors=[];phaseCameraLock=null}if(activeWave<0&&nextWave<phaseWaves.length&&player.x>=phaseWaves[nextWave].trigger)activateWave(nextWave);if(nextWave>=phaseWaves.length&&!bossActivated&&player.x>=4780)activateBoss()}
function phaseBarrier(){return phaseCameraLock===null?Infinity:phaseCameraLock+W-playerHalfWidth()-8}
function actorScale(actor){return actor===enemy ? .44 : actor===jefe ? .90 : .70}
function playerHalfWidth(){const img=currentSet().idle,scale=mobileGameplayScale(selectedCharacter==='casta'?.58:.71);return img.width*scale/2}
function contactDistance(actor){return actor===jefe?62:46}
function inReach(ax,ay,bx,by,reach){return Math.abs(ax-bx)<reach&&Math.abs(ay-by)<24}
function damageEnemy(actor,amount,knockDirection=facing,canBlock=false){if(actor.dead||actor.knocked)return false;const reinforced=actor===enemy||actor===heavyEnemy,blockChance=reinforced?.275:.22,damageMultiplier=actor===jefe?.5:reinforced?.75:1;if(canBlock&&actor.guardTimer>0){actor.state='guard';actor.attackTimer=0;playPunchBlockSfx();return false}if(canBlock&&actor.comboHits===0&&(actor.guardCooldown||0)<=0&&Math.random()<blockChance){actor.guardTimer=55;actor.guardCooldown=78;actor.state='guard';actor.attackTimer=0;playPunchBlockSfx();return false}actor.hp=Math.max(0,actor.hp-amount*damageMultiplier);actor.hitTimer=18;actor.x+=knockDirection*18;playPunchImpactSfx();actor.comboHits=actor.comboTimer>0?actor.comboHits+1:1;actor.comboTimer=42;if(actor.hp===0){actor.dead=true;actor.deadTimer=78;actor.hidden=false;actor.state='dead';actor.attackTimer=0;actor.drinkTimer=0;playKnockoutSfx();return true}if(actor.comboHits>=3){actor.knocked=true;actor.knockTimer=78;actor.comboHits=0;actor.comboTimer=0;actor.state='down';actor.attackTimer=0;playKnockoutSfx()}return true}
function damagePlayer(amount,from){if(playerDead)return;player.hp=Math.max(0,player.hp-amount);playerHitTimer=16;player.x+=from.facing*14;playPunchImpactSfx();if(player.hp===0){playerDead=true;state='dead';attackTimer=0;jumpActive=false;jumpY=0;playKnockoutSfx()}}
function tryPlayerHit(forceKick=false){if(playerAttackLanded||playerDead)return false;const kicking=forceKick||state==='kick'||state==='jumpKick',hitReach=kicking?120:98,damage=kicking?18:14;for(const actor of combatActors()){if(actor.dead)continue;if(Math.abs(actor.x-player.x)<hitReach&&Math.abs(actor.y-player.y)<24){const canBlock=!kicking||actor===enemy||actor===heavyEnemy,damaged=damageEnemy(actor,damage,facing,canBlock);playerAttackLanded=true;return damaged;}}return false}
function startPulidoAttack(kind){pulidoAttack={kind,elapsed:0,landed:false};attackTimer=1;playerAttackLanded=false;state=`${kind}Windup`;zPressed=false;xPressed=false}
function updatePulidoAttack(dt){if(!pulidoAttack)return;const attack=pulidoAttack,timing=pulidoAttackTiming[attack.kind];attack.elapsed+=dt*16.67;zPressed=false;xPressed=false;const impactAt=timing.windup,holdAt=impactAt+timing.impact,recoverAt=holdAt+timing.hold,endAt=recoverAt+timing.recover;if(attack.elapsed<impactAt){state=`${attack.kind}Windup`;return}if(attack.elapsed<holdAt){state=`${attack.kind}Impact`;if(!attack.landed){attack.landed=true;if(tryPlayerHit(attack.kind==='kick'))pulidoHitStopMs=60}return}if(attack.elapsed<recoverAt){state=`${attack.kind}Hold`;return}if(attack.elapsed<endAt){state=`${attack.kind}Recover`;return}pulidoAttack=null;attackTimer=0;state='idle'}
function resolveActorContact(){for(const actor of combatActors()){if(actor.dead||actor.knocked||Math.abs(player.y-actor.y)>=54)continue;const distance=contactDistance(actor)-5,dx=player.x-actor.x;if(Math.abs(dx)<distance)player.x=actor.x+(dx<0?-distance:distance)}}
function tickCombat(dt){if(playerHitTimer>0)playerHitTimer-=dt;combatActors().forEach(actor=>{if(actor.dead){actor.deadTimer-=dt;if(actor.deadTimer<=0)actor.hidden=true;return}if(actor.knocked){actor.knockTimer-=dt;if(actor.knockTimer<=0){actor.knocked=false;actor.state='idle'}return}actor.guardCooldown=Math.max(0,(actor.guardCooldown||0)-dt);if(actor.guardTimer>0)actor.guardTimer-=dt;if(actor.comboTimer>0){actor.comboTimer-=dt;if(actor.comboTimer<=0)actor.comboHits=0}if(actor.hitTimer>0)actor.hitTimer-=dt})}
function enemyStrike(actor,damage){if(actor.attackLanded)return;const hitReach=actor===jefe?130:105;let landed=false;if(!playerDead&&inReach(actor.x,actor.y,player.x,player.y,hitReach)){damagePlayer(damage,actor);landed=true}for(const other of combatActors()){if(other===actor||other.dead||other.knocked)continue;const ahead=(other.x-actor.x)*actor.facing>0;if(ahead&&inReach(actor.x,actor.y,other.x,other.y,hitReach)){damageEnemy(other,damage,actor.facing);landed=true;break}}actor.attackLanded=landed}
function enemyCrowdOffset(actor){let offset=0;for(const other of activeWaveActors){if(other===actor||other.dead||other.knocked)continue;const dx=Math.abs(actor.x-other.x),dy=actor.y-other.y;if(dx<92&&Math.abs(dy)<66)offset+=(dy===0?(actor.aiLane||1):Math.sign(dy))*(66-Math.abs(dy))*.28}return offset}
function anotherEnemyAttacking(actor){return activeWaveActors.some(other=>other!==actor&&!other.dead&&!other.knocked&&other.state==='punch'&&other.attackTimer>4)}
function updateEnemy(dt){if(introPhase!=='done'||comparisonMode)return;normalActors.forEach(actor=>{if(!actor.active||actor.dead||actor.knocked)return;if(actor.guardTimer>0){actor.state='guard';return}const set=enemySet(actor),speed=actor===enemy?.55:.51;actor.attackCooldown=Math.max(0,(actor.attackCooldown||0)-dt);const dx=player.x-actor.x,distance=Math.abs(dx),range=contactDistance(actor)-5,closingLane=Math.max(0,Math.min(1,(distance-42)/105)),targetY=Math.max(laneTop(),Math.min(laneBottom(),player.y+(actor.aiLane||0)*closingLane+enemyCrowdOffset(actor)*closingLane)),dy=targetY-actor.y;actor.y+=Math.sign(dy)*Math.min(Math.abs(dy),.94*dt);actor.facing=dx<0?-1:1;if(actor.hitTimer>0){actor.state='hit';return}if(actor.attackTimer>0){actor.attackTimer-=dt;actor.state='punch';if(actor.attackTimer<20)enemyStrike(actor,8);if(actor.attackTimer<=0)actor.state='idle';return;}const nearLine=Math.abs(actor.y-player.y)<24;if(distance>range||!nearLine){actor.state='walk';if(distance>range&&(nearLine||distance>82))actor.x+=Math.sign(dx)*speed*dt;actor.walkDistance+=Math.abs(speed*dt);actor.walkFrame=Math.floor(actor.walkDistance/enemyWalkFrameStride)%set.walk.length}else if(actor.attackCooldown<=0&&!anotherEnemyAttacking(actor)){actor.state='punch';actor.attackTimer=22;actor.attackLanded=false;actor.attackCooldown=18+Math.random()*18;enemyStrike(actor,8)}else{actor.state='idle';}})}
function updateBossCart(dt){if(!bossCart.active)return false;if(bossCart.phase==='entry'){bossCart.x-=1.75*dt;jefe.x=bossCart.x+160;jefe.y=bossCart.y;jefe.facing=-1;jefe.state='walk';jefe.walkDistance+=1.75*dt;jefe.walkFrame=Math.floor(jefe.walkDistance/enemyWalkFrameStride)%jefePisosRojos.walk.length;if(bossCart.x<=player.x+155){bossCart.phase='throw';bossCart.vx=-5.1;bossCart.throwerX=jefe.x;jefe.state='idle'}return true}bossCart.x+=bossCart.vx*dt;if(!bossCart.hit&&Math.abs(bossCart.x-player.x)<72&&Math.abs(bossCart.y-player.y)<28){bossCart.hit=true;damagePlayer(22,jefe)}if(bossCart.x<player.x-360){bossCart.active=false;jefe.x=bossCart.throwerX;jefe.engaged=false}return bossCart.active}
function updateJefe(dt){if(introPhase!=='done'||comparisonMode||!jefe.active||jefe.dead||jefe.knocked)return;if(updateBossCart(dt))return;if(jefe.guardTimer>0){jefe.state='guard';return}const targetY=Math.max(laneTop(),Math.min(laneBottom(),player.y)),dy=targetY-jefe.y;jefe.y+=Math.sign(dy)*Math.min(Math.abs(dy),.62*dt);const dx=player.x-jefe.x,distance=Math.abs(dx),range=contactDistance(jefe)-5;jefe.facing=dx<0?-1:1;if(!jefe.engaged){jefe.state='idle';if(distance<430)jefe.engaged=true;else return}if(jefe.hitTimer>0){jefe.state='hit';return}if(jefe.drinkTimer>0){jefe.drinkTimer-=dt;jefe.state='drink';if(jefe.drinkTimer<=0){jefe.state='idle';jefe.drinkCooldown=720}return}if(jefe.attackTimer>0){jefe.attackTimer-=dt;jefe.state='punch';if(jefe.attackTimer<25)enemyStrike(jefe,13);if(jefe.attackTimer<=0)jefe.state='idle';return}jefe.drinkCooldown-=dt;if(distance>270&&jefe.drinkCooldown<=0){jefe.state='drink';jefe.drinkTimer=180;return}if(distance>range){jefe.state='walk';jefe.x+=Math.sign(dx)*.36*dt;jefe.walkDistance+=Math.abs(.36*dt);jefe.walkFrame=Math.floor(jefe.walkDistance/enemyWalkFrameStride)%jefePisosRojos.walk.length}else{jefe.state='punch';jefe.attackTimer=30;jefe.attackLanded=false;enemyStrike(jefe,13)}}
function drawActorBar(actor,x,y){const width=58,height=6,ratio=actor.hp/actor.maxHp;ctx.save();ctx.fillStyle='rgba(0,0,0,.72)';ctx.fillRect(x-width/2,y,width,height);ctx.fillStyle=actor.dead?'#63131b':actor===jefe?'#e1a22d':'#43bb59';ctx.fillRect(x-width/2+1,y+1,(width-2)*ratio,height-2);ctx.restore()}
function drawActorImage(actor,img,scale){if(actor.hidden)return;const w=img.width*scale,h=img.height*scale,x=actor.x-cam-w/2,y=actor.y-h;ctx.save();if(actor.dead&&actor.deadTimer<18){if(Math.floor(actor.deadTimer/3)%2===0){ctx.restore();return}}if(actor.facing<0){ctx.translate(x+w,y);ctx.scale(-1,1);ctx.drawImage(img,0,0,w,h)}else ctx.drawImage(img,x,y,w,h);ctx.restore()}
function drawEnemy(){if(introPhase!=='done'||comparisonMode||!enemy.active)return;let img=(enemy.dead||enemy.knocked)?metalero.down:enemy.guardTimer>0?metalero.guard:enemy.hitTimer>0?metalero.hit:metalero.idle;if(enemy.state==='walk')img=metalero.walk[enemy.walkFrame];if(enemy.state==='punch')img=metalero.punch[enemy.attackTimer<22?1:0];drawActorImage(enemy,img,mobileGameplayScale(.44))}
function drawYonki(){if(introPhase!=='done'||comparisonMode||!yonki.active)return;let img=(yonki.dead||yonki.knocked)?yonki2.down:yonki.guardTimer>0?yonki2.guard:yonki.hitTimer>0?yonki2.hit:yonki2.idle;if(yonki.state==='walk')img=yonki2.walk[yonki.walkFrame];if(yonki.state==='punch')img=yonki2.punch;drawActorImage(yonki,img,mobileGameplayScale(.70))}
function drawYonkiRojo(){if(introPhase!=='done'||comparisonMode||!yonkiRojo.active)return;let img=(yonkiRojo.dead||yonkiRojo.knocked)?yonki2Rojo.down:yonkiRojo.guardTimer>0?yonki2Rojo.guard:yonkiRojo.hitTimer>0?yonki2Rojo.hit:yonki2Rojo.idle;if(yonkiRojo.state==='walk')img=yonki2Rojo.walk[yonkiRojo.walkFrame];if(yonkiRojo.state==='punch')img=yonki2Rojo.punch;drawActorImage(yonkiRojo,img,mobileGameplayScale(.70))}
function drawYonkiTres(){if(introPhase!=='done'||comparisonMode||!yonkiTres.active)return;let img=(yonkiTres.dead||yonkiTres.knocked)?yonki3.down:yonkiTres.guardTimer>0?yonki3.guard:yonkiTres.hitTimer>0?yonki3.hit:yonki3.idle;if(yonkiTres.state==='walk')img=yonki3.walk[yonkiTres.walkFrame];if(yonkiTres.state==='punch')img=yonki3.punch;drawActorImage(yonkiTres,img,mobileGameplayScale(.70))}
function drawYonkiTresRubio(){if(introPhase!=='done'||comparisonMode||!yonkiTresRubio.active)return;let img=(yonkiTresRubio.dead||yonkiTresRubio.knocked)?yonki3Rubio.down:yonkiTresRubio.guardTimer>0?yonki3Rubio.guard:yonkiTresRubio.hitTimer>0?yonki3Rubio.hit:yonki3Rubio.idle;if(yonkiTresRubio.state==='walk')img=yonki3Rubio.walk[yonkiTresRubio.walkFrame];if(yonkiTresRubio.state==='punch')img=yonki3Rubio.punch;drawActorImage(yonkiTresRubio,img,mobileGameplayScale(.70))}
function drawYonkiTresNike(){if(introPhase!=='done'||comparisonMode||!yonkiTresNike.active)return;let img=(yonkiTresNike.dead||yonkiTresNike.knocked)?yonki3Nike.down:yonkiTresNike.guardTimer>0?yonki3Nike.guard:yonkiTresNike.hitTimer>0?yonki3Nike.hit:yonki3Nike.idle;if(yonkiTresNike.state==='walk')img=yonki3Nike.walk[yonkiTresNike.walkFrame];if(yonkiTresNike.state==='punch')img=yonki3Nike.punch;drawActorImage(yonkiTresNike,img,mobileGameplayScale(.70))}
function drawKani2(){if(introPhase!=='done'||comparisonMode||!kani2Enemy.active)return;let img=(kani2Enemy.dead||kani2Enemy.knocked)?kani2.down:kani2Enemy.guardTimer>0?kani2.guard:kani2Enemy.hitTimer>0?kani2.hit:kani2.idle;if(kani2Enemy.state==='walk')img=kani2.walk[kani2Enemy.walkFrame];if(kani2Enemy.state==='punch')img=kani2.punch;drawActorImage(kani2Enemy,img,mobileGameplayScale(.70))}
function drawHeavy(){if(introPhase!=='done'||comparisonMode||!heavyEnemy.active)return;let img=(heavyEnemy.dead||heavyEnemy.knocked)?heavy.down:heavyEnemy.guardTimer>0?heavy.guard:heavyEnemy.hitTimer>0?heavy.hit:heavy.idle;if(heavyEnemy.state==='walk')img=heavy.walk[heavyEnemy.walkFrame];if(heavyEnemy.state==='punch')img=heavy.punch;drawActorImage(heavyEnemy,img,mobileGameplayScale(.34))}
function drawJefe(){if(introPhase!=='done'||comparisonMode||!jefe.active)return;let img=(jefe.dead||jefe.knocked)?jefePisosRojos.down:jefe.guardTimer>0?jefePisosRojos.guard:jefe.hitTimer>0?jefePisosRojos.hit:jefePisosRojos.idle;if(jefe.state==='walk')img=jefePisosRojos.walk[jefe.walkFrame];if(jefe.state==='punch')img=jefePisosRojos.punch;if(jefe.state==='drink')img=jefe.drinkTimer>120?jefePisosRojos.drinkRaise:jefePisosRojos.drink;drawActorImage(jefe,img,mobileGameplayScale(.82))}
function drawBossCart(){if(!bossCart.active||!scrapCartImg.complete)return;const w=220,h=w*scrapCartImg.height/scrapCartImg.width,x=bossCart.x-cam-w/2,y=bossCart.y-h;ctx.drawImage(scrapCartImg,x,y,w,h)}
function drawStageClear(){if(!stageClear.active||!stageClearImg.complete)return;const frames=[[0,180],[198,170],[350,200],[534,195],[711,215],[903,215],[1120,350],[1450,355],[1808,360]],frame=frames[Math.min(frames.length-1,Math.floor(stageClear.elapsed/95))],sourceY=260,sourceHeight=220,drawWidth=Math.min(W*.94,500),drawHeight=drawWidth*sourceHeight/frame[1],x=(W-drawWidth)/2,y=(H-drawHeight)/2,fade=Math.max(0,1-Math.max(0,stageClear.elapsed-5000)/1000);ctx.save();ctx.globalAlpha=fade;ctx.drawImage(stageClearImg,frame[0],sourceY,frame[1],sourceHeight,x,y,drawWidth,drawHeight);ctx.restore()}
function drawComparison(){const entries=[['RAFA KING',idleImg,.71],['CASTA',casta.idle,.58],['PULIDO',pulido.idle,.71],['SALVI',salvi.idle,.71],['CAJAMAN',cajaman.idle,.71],['PAKO',pako.idle,.71]];const baseY=H*.90;ctx.save();ctx.fillStyle='rgba(0,0,0,.60)';ctx.fillRect(0,H*.73,W,H*.27);entries.forEach(([name,img,scale],i)=>{const w=img.width*scale,h=img.height*scale,x=W*(i+.5)/entries.length-w/2,y=baseY-h;ctx.drawImage(img,x,y,w,h);ctx.fillStyle='#fff';ctx.font='bold 12px monospace';ctx.textAlign='center';ctx.fillText(name,x+w/2,baseY+18)});ctx.restore();}
function update(dt){if(comparisonMode)return;if(introRunning()){updateIntro(dt);return;}tickCombat(dt);if(!stageClear.active&&!stageClear.finished&&jefe.dead&&jefe.hidden)startStageClear();if(stageClear.active){stageClear.elapsed+=dt*16.67;if(stageClear.elapsed>=5000)stageClearCheer.volume=.45*Math.max(0,1-(stageClear.elapsed-5000)/1000);if(stageClear.elapsed>=6000){stageClear.active=false;stageClear.finished=true;stageClearCheer.pause();stageClearCheer.currentTime=0}updateCamera();return}if(playerDead){updateCamera();return}const previousX=player.x,previousY=player.y;const speed=1.35*dt,vSpeed=1.10*dt;
 if(!jumpActive && attackTimer<=0 && crouchTimer<=0){
   if(comboPressed){state='crouch';crouchTimer=18;comboPressed=false;zPressed=false;xPressed=false;}
   else {
    const movingH=keys['arrowleft']||keys['a']||keys['arrowright']||keys['d']; const movingV=keys['arrowup']||keys['w']||keys['arrowdown']||keys['s'];
    if(movingH||movingV){state='walk';} else {state='idle';walkClock=0;walkFrame=0;walkDistance=0;}
    if(keys['arrowleft']||keys['a']){player.x-=speed;facing=-1}else if(keys['arrowright']||keys['d']){player.x+=speed;facing=1}
    if(keys['arrowup']||keys['w'])player.y-=vSpeed;if(keys['arrowdown']||keys['s'])player.y+=vSpeed;player.y=Math.max(laneTop(),Math.min(laneBottom(),player.y));
    if(zPressed){if(selectedCharacter==='pulido')startPulidoAttack('punch');else{attackTimer=12;state='punch';playerAttackLanded=false;zPressed=false}}else if(xPressed){if(selectedCharacter==='pulido')startPulidoAttack('kick');else{attackTimer=9;state='kick';playerAttackLanded=false;xPressed=false}}
   }
 }
 if(!jumpActive && crouchTimer>0){state='crouch';crouchTimer--;if(crouchTimer<=0){state='idle';walkClock=0;walkFrame=0;}}
 if(!jumpActive && attackTimer>0&&selectedCharacter!=='pulido'){state=state==='kick'?'kick':'punch';attackTimer--;tryPlayerHit();if(attackTimer<=0){state='idle';walkClock=0;walkFrame=0;}}
 if(!jumpActive&&selectedCharacter==='pulido'&&pulidoAttack)updatePulidoAttack(dt);
 if(jumpActive){if(keys['arrowleft']||keys['a']){player.x-=speed;facing=-1;}else if(keys['arrowright']||keys['d']){player.x+=speed;facing=1;}if(keys['arrowup']||keys['w'])player.y-=vSpeed;if(keys['arrowdown']||keys['s'])player.y+=vSpeed;player.y=Math.max(laneTop(),Math.min(laneBottom(),player.y));if(xPressed){jumpKick=true;jumpRecover=false;playerAttackLanded=false;state='jumpKick';xPressed=false}else if(!jumpKick)state='jump';jumpT+=dt/1000;let pp=Math.min(1,jumpT/0.060);jumpY=-Math.sin(pp*Math.PI)*H*0.09;if(jumpKick){if(jumpT<0.033){state='jumpKick';if(tryPlayerHit()&&selectedCharacter==='pulido')pulidoHitStopMs=60;}else if(jumpT<0.051){state='jumpRecover';jumpRecover=true;}else{state='jumpRecover';}}if(pp>=1){jumpActive=false;jumpY=0;jumpKick=false;jumpRecover=false;state='idle';walkClock=0;walkFrame=0;}}
 player.x=Math.max(50,Math.min(worldW-80,player.x));resolveWorldCollision(previousX,previousY);updatePhaseWaves();player.x=Math.min(player.x,phaseBarrier());resolveActorContact();const walkedDistance=Math.hypot(player.x-previousX,player.y-previousY),walkSet=currentSet().walk;if(!jumpActive&&state==='walk'&&walkedDistance>.01){const smoothWalk=walkSet===rafaWalkCycle||walkSet===pulido.walk||walkSet===salvi.walk||walkSet===casta.walk||walkSet===pako.walk||walkSet===cajaman.walk;const frameStride=smoothWalk?9:walkSet.length===3?13:10;walkDistance+=walkedDistance;walkFrame=Math.floor(walkDistance/frameStride)%walkSet.length;}updateEnemy(dt);updateJefe(dt);updateCamera();}

function drawHudName(label,x,y,width){ctx.save();ctx.beginPath();ctx.rect(x+4,y+2,width-8,19);ctx.clip();ctx.translate(x+7,y+18);ctx.transform(1,0,-.20,1,0,0);ctx.fillStyle='rgba(255,255,255,.62)';ctx.font='italic 900 15px Impact,Arial Black,sans-serif';ctx.textBaseline='alphabetic';ctx.fillText(label,0,0);ctx.restore()}
function drawHudBar(x,y,width,ratio,color,label){ctx.save();ctx.fillStyle='rgba(0,0,0,.74)';ctx.fillRect(x,y,width,23);ctx.fillStyle=color;ctx.fillRect(x+3,y+3,(width-6)*Math.max(0,Math.min(1,ratio)),17);drawHudName(label,x,y,width);ctx.restore()}
function ui(){if(introPhase!=='done'||comparisonMode||stageClear.active)return;const playerWidth=Math.min(110,W*.20),enemyWidth=Math.min(95,W*.17),playerName={rafa:'RAFA KING',casta:'CASTA',pulido:'PULIDO',salvi:'SALVI',cajaman:'CAJAMAN',pako:'PAKO'}[selectedCharacter];drawHudBar(18,18,playerWidth,player.hp/player.maxHp,'#2fc760',playerName);combatActors().filter(actor=>!actor.hidden).forEach((actor,index)=>drawHudBar(W-enemyWidth-18,18+index*29,enemyWidth,actor.hp/actor.maxHp,actor===jefe?'#e1a22d':'#d94040',actor.name))}
let last=performance.now();function loop(t){let dt=Math.min(2,(t-last)/16.67);last=t;if(pulidoHitStopMs>0){pulidoHitStopMs=Math.max(0,pulidoHitStopMs-dt*16.67)}else update(dt);applyViewportTransform();drawBackground();ctx.fillStyle='rgba(0,0,0,.08)';ctx.fillRect(0,groundY(),W,H-groundY());drawIntroCar();if(comparisonMode)drawComparison();else{drawEnemy();drawYonki();drawYonkiRojo();drawYonkiTres();drawYonkiTresRubio();drawYonkiTresNike();drawKani2();drawHeavy();drawJefe();drawBossCart();drawPlayer();drawStageClear();}ui();requestAnimationFrame(loop)}

function selectCharacter(name){selectedCharacter=name;selectionMusic.pause();selectionMusic.currentTime=0;document.getElementById('selectScreen').style.display='none';bossIntroActive=false;bossIntroScreen.classList.remove('show');player.x=180;player.y=laneBottom();player.hp=player.maxHp;playerDead=false;playerHitTimer=0;stageClear={active:false,elapsed:0,finished:false};stageClearCheer.pause();stageClearCheer.currentTime=0;stageClearCheer.volume=.45;normalActors.forEach((actor,index)=>{Object.assign(actor,{x:1160+index*350,y:laneBottom(),state:'idle',walkDistance:0,walkFrame:0,attackTimer:0,attackLanded:false,hitTimer:0,dead:false,deadTimer:0,hidden:true,hp:actor.maxHp,comboHits:0,comboTimer:0,knocked:false,knockTimer:0,strafeClock:0,active:false})});jefe.x=worldW-260;jefe.y=laneBottom();jefe.state='idle';jefe.walkDistance=0;jefe.walkFrame=0;jefe.attackTimer=0;jefe.attackLanded=false;jefe.hitTimer=0;jefe.dead=false;jefe.deadTimer=0;jefe.hidden=true;jefe.hp=jefe.maxHp;jefe.engaged=false;jefe.drinkTimer=0;jefe.drinkCooldown=480;[...normalActors,jefe].forEach(actor=>{actor.comboHits=0;actor.comboTimer=0;actor.knocked=false;actor.knockTimer=0;actor.strafeClock=0;actor.active=false});activeWave=-1;nextWave=0;activeWaveActors=[];phaseCameraLock=null;bossActivated=false;cam=0;facing=1;state='idle';walkFrame=0;walkClock=0;walkDistance=0;attackTimer=0;playerAttackLanded=false;crouchTimer=0;jumpActive=false;jumpT=0;jumpY=0;jumpKick=false;jumpRecover=false;pulidoAttack=null;pulidoHitStopMs=0;showMapScreen();}
const selectCharacterBase=selectCharacter;
selectCharacter=function(name){selectionMusic.mapResumeTime=selectionMusic.currentTime;stopPhaseMusic();bossCart={active:false,phase:'none',x:0,y:0,vx:0,hit:false,throwerX:0};return selectCharacterBase(name)};
const touchControls=document.createElement('div');
touchControls.id='touchControls';
const touchPad=document.createElement('div'),touchActions=document.createElement('div');
touchPad.className='touchPad';touchActions.className='touchActions';
const joystickBase=document.createElement('div'),joystickStick=document.createElement('div');
joystickBase.className='joystickBase';joystickStick.className='joystickStick';
joystickBase.append(joystickStick);touchPad.append(joystickBase);
const touchButtons=[['z','PUÑO','',touchActions],['x','PATADA','',touchActions],['c','SALTO','',touchActions]];
function touchDown(key){keys[key]=true;if(key==='z')zPressed=true;if(key==='x')xPressed=true;if(keys.z&&keys.x&&!comboHeld){comboPressed=true;comboHeld=true}if(key==='c'&&!jumpActive&&!introRunning()){jumpActive=true;jumpT=0;jumpY=0;jumpKick=false;state='jump'}}
function touchUp(key){keys[key]=false;if(!keys.z||!keys.x)comboHeld=false}
function setJoystickDirection(dx,dy){const dead=.24;keys.arrowleft=dx<-dead;keys.arrowright=dx>dead;keys.arrowup=dy<-dead;keys.arrowdown=dy>dead}
function moveJoystick(event){const bounds=joystickBase.getBoundingClientRect(),cx=bounds.left+bounds.width/2,cy=bounds.top+bounds.height/2;let dx=(event.clientX-cx)/(bounds.width*.34),dy=(event.clientY-cy)/(bounds.height*.34);const distance=Math.hypot(dx,dy);if(distance>1){dx/=distance;dy/=distance}joystickStick.style.transform=`translate(${dx*30}px,${dy*30}px)`;setJoystickDirection(dx,dy)}
function releaseJoystick(event){if(event.pointerId!==joystickBase.pointerId)return;joystickBase.releasePointerCapture?.(event.pointerId);joystickBase.pointerId=null;joystickStick.style.transform='translate(0,0)';setJoystickDirection(0,0)}
joystickBase.addEventListener('pointerdown',event=>{event.preventDefault();joystickBase.pointerId=event.pointerId;joystickBase.setPointerCapture?.(event.pointerId);moveJoystick(event)});
joystickBase.addEventListener('pointermove',event=>{if(event.pointerId===joystickBase.pointerId)moveJoystick(event)});
['pointerup','pointercancel','lostpointercapture'].forEach(type=>joystickBase.addEventListener(type,releaseJoystick));
touchButtons.forEach(([key,label,className,parent])=>{const button=document.createElement('button');button.type='button';button.className=`touchButton ${className}`;button.dataset.key=key;button.textContent=label;button.addEventListener('pointerdown',event=>{event.preventDefault();button.classList.add('pressed');button.setPointerCapture?.(event.pointerId);touchDown(key)});['pointerup','pointercancel','lostpointercapture'].forEach(type=>button.addEventListener(type,event=>{event.preventDefault();button.classList.remove('pressed');touchUp(key)}));parent.append(button)});
touchControls.append(touchPad,touchActions);document.body.append(touchControls);
setInterval(()=>touchControls.classList.toggle('visible',introPhase==='done'&&!playerDead),100);
Promise.all([bg,carImg,scrapCartImg,stageClearImg,idleImg,jumpImg,punchImg,kickImg,airKickImg,airRecoverImg,crouchImg,rafaHitImg,rafaDownImg,rafaWalkCenter,rafaWalkOpposite,rafaWalkTransitionA,rafaWalkTransitionB,...walkImgs,...Object.values(casta),...Object.values(pulido),...Object.values(salvi),...Object.values(cajaman),...Object.values(pako),...Object.values(metalero),...Object.values(yonki2),...Object.values(yonki2Rojo),...Object.values(yonki3),...Object.values(yonki3Rubio),...Object.values(yonki3Nike),...Object.values(kani2),...Object.values(heavy),...Object.values(jefePisosRojos)].flat().map(im=>new Promise(r=>im.complete?r():im.onload=r))).then(()=>requestAnimationFrame(loop));

